app/core/urls.py
"""Main Url's module"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/worldcup/', include(('worldcup.urls', 'worldcup'), namespace="worldcup")),
    path('api/auth/', include(('users.urls', 'users'), namespace="users")),
    path('worldcup/qatar/', include(('qatar_2022.urls', 'qatar_2022'), namespace="qatar_2022")),
    path('', views.index, name='index'),
] 

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/qatar_2022/urls.py
from django.urls import path

from .views import IndexView, PoolMatchesView, LoginView, ProfileView, RetrievePoolView, SignupView, ManageMatchesView, RetrievePoolKeyView, RankingsView, InfoView, RetrieveRakingPoolView


app_name = 'qatar_2022'

urlpatterns = [
    #path('', views.index, name='index'),
    #path('pool_matches/', views.pool_matches, name='pool_matches'),
    #path('login/', views.login, name='login'),
    path('', IndexView.as_view(), name='index'),
    path('pool_matches/', PoolMatchesView.as_view(), name='pool_matches'),
    path('login/', LoginView.as_view(), name='login'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('retrieve_pool/<int:id>/', RetrievePoolView.as_view(), name='retrieve_pool'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('manage_matches/', ManageMatchesView.as_view(), name='manage_matches'),
    path('pool_key_matches/<int:id>/', RetrievePoolKeyView.as_view(), name='pool_key_matches'),
    path('rankings/', RankingsView.as_view(), name='rankings'),
    path('info/', InfoView.as_view(), name='info'),
    path('retrieve_pool_ranking/<int:id>/', RetrieveRakingPoolView.as_view(), name='retrieve_pool_ranking'),
]

app/users/urls.py
"""Users Urls"""

# Django rest framework
from rest_framework.routers import DefaultRouter

#Django
from django.urls import path, include

# Views
from .views import users as user_views

router = DefaultRouter()
router.register(r'users', user_views.UserViewSet, basename='users')

urlpatterns = [
    path('', include(router.urls))
]

app/worldcup/urls.py
"""Teams Urls"""

# Django rest framework
from rest_framework.routers import DefaultRouter

#Django
from django.urls import path, include

# Views
from .views import teams as teams_views
from .views import worldcup_matches as worldcup_matches_views
from .views import worldcup_pools as worldcup_pools_views
from .views import pool_matches as pool_matches_views
from .views import worldcup_key_matches as worldcup_key_matches_views
from .views import pools_key_matches as pool_key_matches_views
from .views import pool_group_teams as pool_group_teams_views

router = DefaultRouter()
router.register(r'teams', teams_views.TeamViewSet, basename='teams')
router.register(r'worldcup_matches', worldcup_matches_views.WorldcupMatchViewSet, basename='worldcup_matches')
router.register(r'worldcup_pools', worldcup_pools_views.WorldcupPoolViewSet, basename='worldcup_pools')
router.register(r'pool_matches', pool_matches_views.PoolMatchViewSet, basename='pool_matches')
router.register(r'worldcup_key_matches', worldcup_key_matches_views.WorldcupKeyMatchViewSet, basename='worldcup_key_matches')
router.register(r'pool_key_matches', pool_key_matches_views.PoolKeyMatchViewSet, basename='pool_key_matches')
router.register(r'pool_group_teams', pool_group_teams_views.PoolTeamViewSet, basename='pool_group_teams')

urlpatterns = [
    path('', include(router.urls))
]

app/users/models/users.py
"""User models."""
from django.db import models

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """User model."""
    email = models.EmailField(
        'email adress',
        unique=True,
        error_messages={
            'unique': 'A user with that email already exists.'
        }
    )
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']
    credits = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.username

app/users/views/users.py
"""Users views."""

# Django REST Framework
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, viewsets, mixins
from rest_framework.decorators import action

# Permissions
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
)
#from cride.users.permissions import IsAccountOwner

# Serializers 
from users.serializers.users import UserSignUpModelSerializer, UserModelSerializer, UserLoginSerializer, RemoveCreditsSerializer, UserUpdatePasswordModelSerializer

# Models
from users.models.users import User

class UserViewSet(mixins.RetrieveModelMixin,
                    mixins.UpdateModelMixin,
                    viewsets.GenericViewSet):
    """User view set.

    Handle sign up, login and account verification.
    """
    queryset = User.objects.filter(is_active=True)
    #serializer_class = UserModelSerializer
    lookup_field = 'username'
    
    # solo accesible por usuario    
    """
    def get_permissions(self):
        if self.action in ['signup', 'login']:
            permissions = [AllowAny]
        elif self.action in ['retrieve', 'update', 'partial_update']:
            permissions = [IsAuthenticated, ] #IsAccountOwner]
        else:
            permissions = [IsAuthenticated]
        return [p() for p in permissions]
    """
    def get_serializer_class(self):
        """Return serializer based on actions"""
        if self.action == 'signup':
            return UserSignUpModelSerializer
        return UserModelSerializer


    @action(detail=False, methods=['post'])
    def signup(self, request):
        """User sign up."""
        serializer = UserSignUpModelSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        data = UserModelSerializer(user).data
        return Response(data, status=status.HTTP_201_CREATED)

    @action(detail=False, methods=['patch'])
    def update_password(self, request):
        """User update password."""
        users = User.objects.all()
        serializer = UserUpdatePasswordModelSerializer(instance = users, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        data = UserModelSerializer(user).data
        return Response(data, status=status.HTTP_201_CREATED)

    
    @action(detail=False, methods=['post'])
    def login(self, request):
        """User log in."""
        serializer = UserLoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user, token = serializer.save()
        data = {
            'user': UserModelSerializer(user).data,
            'access_token': token
        }
        
        response = Response(data, status=status.HTTP_200_OK)
        response.set_cookie(key='access_token', value=token, httponly=True, samesite='None')
        print(data)
        return response

    @action(detail=False, methods=['get'])
    def logout(self, request):
        """User log out."""
        response = Response(status=status.HTTP_200_OK)
        response.delete_cookie(key='access_token')
        print("sesion cerrada")
        return response

    @action(detail=True, methods=['patch'])
    def remove_credits(self, request, *args, **kwargs):
        """Remove credits from user."""
        user = self.get_object()
        serializer = RemoveCreditsSerializer(instance=user, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        data = UserModelSerializer(user).data
        return Response(data, status=status.HTTP_200_OK)

app/templates/users/login.html
{% extends "layout.html" %}

{% load static %}

{% block body %}
   <section id="login-content">
        <div id="login-banner-container">
            <div class="capa"></div>
            <div class="banner-content">
                <section id="login-container-section">
                    <div id="login-container">
                        <div id="login-container-title">
                            <h1 id="login-title">Iniciar Sesión</h1>
                        </div>
                        <div id="login-container-form">
                            <div id="login-error-msg-container">
                                <label id="login-error-msg" for=""></label>
                            </div>
                                <div class="login-input-container">
                                    <input type="email" class="form-control" id="login-user-email" name="email" placeholder="Correo electrónico">
                                </div>
                                <div class="">
                                    <input type="password" class="form-control" id="login-user-password" name="password" placeholder="Contraseña">
                                </div>
                                <div class="">
                                    <button id="user-login-btn" type="submit" class="">Iniciar Sesión</button>
                                </div>
                                <div class="register-link-container">
                                    <a href="{% url 'qatar_2022:signup' %}" id="register-link">Regístrate</a>
                                </div>
                        </div>
                    </div>
                </section>
            </div> 
        </div>
    </section>
{% endblock body %}

{% block script %}
    <link rel="stylesheet" href="{% static 'css/login_styles.css' %}">
    <script src="{% static '/js/users.js' %}"></script>
{% endblock %}

app/templates/users/profile.html
{% extends "layout.html" %}

{% load static %}

{% block body %}
   <section id="index-content">
        <div id="profile-banner-container">
            <div class="capa"></div>
            <div class="profile-content">
                <section id="profile-container-section">
                    <div id="profile-container">
                        <div id="profile-logout-container">
                            <div id="profile-logout-btn-container">
                                <h5 id="profile-logout-title">Cerrar Sesión</h4>
                            </div>
                        </div>
                        <div id="profile-username-container">
                            <h4 id="profile-username-title"></h4>
                        </div>
                        <div id="profile-pools-container">
                            <div id="profile-pools-info-container">
                                <div id="profile-pools-info-title-container">
                                    <h4 id="profie-pools-info-title">Quinielas</h4>
                                </div>
                                <div id="profile-user-pools-container"></div>
                            </div>
                        
                        </div>
                        <div id="profile-credits-container">
                            <h4 id="profile-credits-title"></h4>
                        </div>
                        {% if worldcup_started == False %}
                        <div id="profile-pool-creation-btn-container">
                            <a id="profile-pool-creation-btn-link" href="{% url 'qatar_2022:pool_matches' %}">
                                <div id="profile-pool-creation-btn">
                                    <h4 id="profile-pool-creation-btn-title">Crear Quiniela</h4>
                                </div>
                            </a>
                            <a href="https://api.whatsapp.com/send?phone=584149534208&text=Quisiera adquirir creditos de quiniela">
                                <div id="profile-pool-credits-btn">
                                    <h4 id="profile-pool-credits-btn-title">Adquirir Creditos</h4>
                                </div>
                            </a>

                            <div id="credits-info-container">
                                <label for="" id="credits-info-title">Debes adquirir creditos para crear tu quiniela</label>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </section>
            </div> 
        </div>
   </section>
{% endblock body %}

{% block script %}
    <script src="{% static '/js/profile.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/profile_styles.css' %}">
{% endblock %}

app/templates/users/signup.html
{% extends "layout.html" %}

{% load static %}

{% block body %}
   <section id="signup-content">
        <div id="signup-banner-container">
            <div class="capa"></div>
            <div class="banner-content">
                <section id="signup-container-section">
                    <div id="signup-container">
                        <div id="signup-container-title">
                            <h1 id="signup-title">Regístrate</h1>
                        </div>

                        <div id="signup-container-form">
                                <div id="signup-error-msg-container">
                                    <label id="signup-error-msg" for=""></label>
                                </div>
                                
                                <div class="signup-input-container">
                                    <input type="email" class="" id="signup-user-email" name="email" placeholder="Correo electrónico">
                                </div>
                                <div class="signup-input-container">
                                    <input type="email" class="" id="signup-user-username" name="email" placeholder="Username">
                                </div>
                                <div class="">
                                    
                                    <input type="password" class="" id="signup-user-password" name="password" placeholder="Contraseña">
                                </div>
                                <div class="">
                                    <input type="password" class="" id="signup-user-password-confirmation" name="password-confirmation" placeholder="Confirmación de contraseña">
                                </div>
                                <div class="">
                                    <button id="user-signup-btn" type="submit" class="">Registrarte</button>
                                </div>
                                <div class="login-link-container">
                                    <a href="{% url 'qatar_2022:login' %}" id="login-link">Iniciar sesión</a>
                                </div>
                        </div>
                    </div>
                </section>
            </div> 
        </div>
    </section>
{% endblock body %}

{% block script %}
    <link rel="stylesheet" href="{% static 'css/signup_styles.css' %}">
    <script src="{% static '/js/users.js' %}"></script>
{% endblock %}