app/core/urls.py
"""Main Url's module"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/worldcup/', include(('worldcup.urls', 'worldcup'), namespace="worldcup")),
    path('api/auth/', include(('users.urls', 'users'), namespace="users")),
    path('worldcup/qatar/', include(('qatar_2022.urls', 'qatar_2022'), namespace="qatar_2022")),
    path('', views.index, name='index'),
] 

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/qatar_2022/urls.py
from django.urls import path

from .views import IndexView, PoolMatchesView, LoginView, ProfileView, RetrievePoolView, SignupView, ManageMatchesView, RetrievePoolKeyView, RankingsView, InfoView, RetrieveRakingPoolView


app_name = 'qatar_2022'

urlpatterns = [
    #path('', views.index, name='index'),
    #path('pool_matches/', views.pool_matches, name='pool_matches'),
    #path('login/', views.login, name='login'),
    path('', IndexView.as_view(), name='index'),
    path('pool_matches/', PoolMatchesView.as_view(), name='pool_matches'),
    path('login/', LoginView.as_view(), name='login'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('retrieve_pool/<int:id>/', RetrievePoolView.as_view(), name='retrieve_pool'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('manage_matches/', ManageMatchesView.as_view(), name='manage_matches'),
    path('pool_key_matches/<int:id>/', RetrievePoolKeyView.as_view(), name='pool_key_matches'),
    path('rankings/', RankingsView.as_view(), name='rankings'),
    path('info/', InfoView.as_view(), name='info'),
    path('retrieve_pool_ranking/<int:id>/', RetrieveRakingPoolView.as_view(), name='retrieve_pool_ranking'),
]

app/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img/Qatar2022.png' %}">
   
    <title>Worldcup Qatar 2022</title>
    {% block javascript %}
        <script defer src="{% static 'js/menu.js' %}"></script>
    {% endblock javascript %}
</head>
<body>
    <div id="website-area">
        <header id="header" class="menu-fixed">
            <nav id="nav" class="menu-desplegable">
                <div id="logo">
                    <a href="{% url 'qatar_2022:index' %}">
                        <img src="{% static 'img/Qatar2022.png' %}" alt="Qatar2022">
                    </a>
                </div>
                <div class="menu-btn-nav">
                    <div class="menu-btn">
                      <div class="btn__burger"></div>
                    </div>
                </div>


                <ul id="nav-menu">
                    <li>
                        <a href="{% url 'qatar_2022:info' %}">INFORMACIÓN</a>
                    </li>
                    <li>
                        <a href="{% url 'qatar_2022:rankings' %}">RANKINGS</a>
                    </li>
                    
                    <li>
                        <a href="">MATCHES</a>
                    </li>
                </ul>
                <ul id="nav-menu-user">
                    <li>
                        <a href="{% url 'qatar_2022:profile' %}" title="user" id="user-icon" >
                            <img src="{% static 'img/user.png' %}" alt="user">
                        </a>
                    </li>
                </ul>
            </nav>
        </header>
            
        <div class="body">
            {% block body %}
            {% endblock %}
            
        </div>
        <!--
        <footer>
            <div id="footer-container">
                juannajulvillegas@gmail.com
            </div>
        </footer>
        -->
    </div>
    {% block script %}
      
    {% endblock %}
</body>
</html>